{% set name = "pygaze" %}
{% set pypiname = "python-" + name %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: bf5e52fd61f725c4a3b64e08beaeb433f00b89420dd6adecd7038fd78ac73546

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygaze
    - pygaze._display
    - pygaze._eyetracker
    - pygaze._joystick
    - pygaze._keyboard
    - pygaze._logfile
    - pygaze._misc
    - pygaze._mouse
    - pygaze._screen
    - pygaze._sound
    - pygaze._time
    - pygaze.plugins

about:
  home: http://www.pygaze.org/
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A Python library for eye tracking
  dev_url: https://github.com/esdalmaijer/PyGaze
  doc_url: http://www.pygaze.org/

extra:
  recipe-maintainers:
    - dschreij
    - smathot
